using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class fallingCake : MonoBehaviour
{
    /* todo
     * - Kameraf체hrung: evtl Kamera rotieren und Tisch zeigen
     * - Cake steuern
     * - Wo werden die B채llchen aufkommen beim Kuchen? Wieder Licht setzen oder X f체r Aufkomm-Stelle
     * - WebGL Export: genug Zeit einplanen, Fehler sind wohl 체blich 
     */
    public GameObject cake;
    private void OnTriggerEnter(Collider collision)
    {
        if (collision.gameObject.tag == "Cake")
        {
            Rigidbody cubeRigidbody = collision.GetComponent<Rigidbody> ();
            cubeRigidbody.isKinematic = false;
        }
    }
}
